### ISSUE TITLE
Update Firefox Add-on to v1.0.0

### ISSUE THREAD

**Issue by wadjoh** [homerchen19/github-file-icon#71]
The Chrome version of github-file-icon is on v1.0.0 and supports custom domains. But the Firefox add-on is currently on v0.8.1 (last updated Jan 29, 2019) which does not have the custom domains feature.

Are there plans for the Firefox add-on to be implemented?

Thanks for this extension, by the way. It's one of the few I love a lot.

**Comment by homerchen19** [comment]
Hi @wadjoh, I'm so sorry for the late reply. The extension on Firefox has been updated to version `v1.1.0`. Hope you enjoy it, and I'm terribly sorry for this.
