### ISSUE TITLE
Suggestion: replace in the repo and extensions names the 'Icon' to 'Icons'

### ISSUE THREAD

**Issue by darkred** [homerchen19/github-file-icon#83]
Greetings

First of all, I like the extension a lot, thank you.

I'd like to make a suggestion:
replace in the repo and extensions names, the word 'Icon' to 'Icons' i.e.
the repo: `github-file-icons`
the Chrome extension: `File Icons for GitHub and GitLab`
the Firefox extension: `File Icons for GitHub, GitLab and Bitbucket`.

My reasoning is apparent: the extensions don't affect just 1 icon, but multiple icons (in repo file listings).

Thank you

**Comment by homerchen19** [comment]
It makes sense. I'll change the names. Thanks for your suggestion.
